# Build dockerfile on change
name: Build Docker

on:
  push:
    paths:
    - 'env/genome.Dockerfile'
    - '.github/workflows/build.yml'
  pull_request:
    paths:
    - 'env/genome.Dockerfile'
    - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build and Publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: andersenlab/genomes
        tag: "${{ steps.current-time.formattedTime }}"
        username: ${{ secrets.KSE_DOCKER_USER }}
        password: ${{ secrets.KSE_DOCKER_PASS }}
        snapshot: true
        dockerfile: genome.Dockerfile
        workdir: "env"
        tags: "latest"
